In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [2]:
#Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

"""
yes, there is a difference , list_ 's data type is 'list' and array_list's datatype is ndarray"""
print("typr of list_ is : ",type(list_))
print("typr of array_list is : ",type(array_list))



typr of list_ is :  <class 'list'>
typr of array_list is :  <class 'numpy.ndarray'>


In [3]:
#Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.


print("Types of each element of list_ variable ")
for i in list_:
    print(type(i))
    
print("Types of each element of array_list variable ")
for i in array_list:
    print(type(i))    
    
    
    

Types of each element of list_ variable 
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Types of each element of array_list variable 
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [4]:
''' Q3. Considering the following changes in the variable, array_list: 
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list. '''


""" Yes, there is a change in datatypes in array_list variable, all the element's datatype change into integer type. But list_ variable have the same data
type as previous"""

array_list = np.array(object = list_, dtype = int)

print("Types of each element of list_ variable ")
for i in list_:
    print(type(i))
    
print("Types of each element of array_list variable ")
for i in array_list:
    print(type(i))    
    

Types of each element of list_ variable 
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Types of each element of array_list variable 
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [5]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [6]:
"""Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size
"""
''' shape return a tuple which consist the number_of_rows and number_of_columns, where as size return the total number of elements of array which is the 
product of number_of_rows and number_of_columns.'''
print(np.shape(num_array))
print(num_array.size)

(2, 3)
6


In [8]:
"""Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]
"""

num_arr = np.zeros((3,3))
print(num_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
"""Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]
"""

num_arr1 = np.eye(5)
print(num_arr1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
